version: "2"
services:
  server:
    image: daocloud.io/jaggerwang/zqc-server-demo
    environment:
      ZQC_ENV: production
      ZQC_SERVER_DEBUG: "false"
      ZQC_LOG_LEVEL: info
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: daocloud.io/jaggerwang/mongodb
  redis:
    image: daocloud.io/jaggerwang/redis
